config/routes.rb
Rails.application.routes.draw do

          resources :users
          resources :microposts, only: [:create, :destroy] 
          resources :automotives
          resources :caterings
          resources :finances
          resources :its

          root 'static_pages#home'
          get 'search'  => 'static_pages#search'
          get 'help'    => 'static_pages#help'
          get 'about'   => 'static_pages#about'
          get 'contact' => 'static_pages#contact'
          get 'signup'  => 'users#new'
          get    'login'   => 'sessions#new'
          post   'login'   => 'sessions#create'
          delete 'logout'  => 'sessions#destroy'
get 'catering'=>'caterings#index'
get 'automotive'=>'automotives#index'
get 'it'=>'its#index'
get 'finance'=>'finances#index'

end

app/models/automotive.rb
class Automotive < ActiveRecord::Base
	
end

app/models/catering.rb
class Catering < ActiveRecord::Base
end

app/models/finance.rb
class Finance < ActiveRecord::Base
end

app/models/it.rb
class It < ActiveRecord::Base
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
      belongs_to :user    # Association with User

      validates :user_id, presence: true
      validates :content, presence: true, length: { maximum: 140 }
      default_scope -> { order(created_at: :desc) }
    end

app/models/profession.rb
class Profession < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  attr_accessor :remember_token
		before_save { self.email = email.downcase }
      validates :name, presence: true, length: { in: 9..30 }
      VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
      validates :email, presence: true, 
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }

      validates :password, presence: true, length: { minimum: 6 }
      validates :password_confirmation, presence: true
      has_secure_password

       # Returns the hash digest of a string.
      def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
      end

      # Returns a random token.
      def User.new_token
        SecureRandom.urlsafe_base64
      end

      # Remembers a user in the database for use in persistent sessions.
      def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
      end

       # Returns true if the given token matches the digest.
      def authenticated?(remember_token)
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
      end

      # Forgets a user.
       def forget
          update_attribute(:remember_digest, nil)
       end
       def feed
                Micropost.where("user_id = ?", id)
            end
end  

app/controllers/caterings_controller.rb
class CateringsController < ApplicationController
	def index
		@caterings=Catering.all
	end
end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
	def index
		@finances=Finance.all
	end
end

app/controllers/its_controller.rb
class ItsController < ApplicationController
	def index
		@its=It.all
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

      def new
      end

      def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
          remember user       # NEW LINE
          redirect_to user
        else
          flash.now[:danger] = 'Invalid email/password combination'
          render 'new'
        end
      end

      def destroy
        log_out if logged_in?
        redirect_to root_url
      end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  @users = User.paginate(page: params[:page])
  end

      def show
        @user = User.find(params[:id])
       @microposts = @user.microposts.paginate(page: params[:page])
      end

      def new
        @user = User.new
      end

      def edit
    @user = User.find(params[:id])
  end

  
       def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      remember @user
      flash[:success] = "Save"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
end 
end


      def create
        secure_params = params.require(:user).permit(:name, :email, 
                                  :password, :password_confirmation)
        @user = User.new(secure_params)
        if @user.save
          remember @user      
          flash[:success] = "Welcome to Easy Job!"   
          redirect_to @user  
        else
          render 'new'
        end
      end

      private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
    def signed_in_user
      unless signed_in?
    store_location
    redirect_to signin_url, notice: "Please sign in."
  end

end
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
end

   


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/automotives_helper.rb
module AutomotivesHelper
end

app/helpers/caterings_helper.rb
module CateringsHelper
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/helpers/its_helper.rb
module ItsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	# Remembers a user in a persistent session.
      def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
      end

       # Returns the user corresponding to the remember token cookie.
      def current_user
        if (user_id = cookies.signed[:user_id])
           user = User.find_by(id: user_id)
           if user && 
                user.authenticated?(cookies[:remember_token])
            @current_user = user
          end
        end
      end



      # Returns true if a user is logged in, false otherwise.
      def logged_in?
        !current_user.nil?
      end


      # Returns true if the given user is the current user.
      def current_user?(user)
        user == current_user
      end

      def logged_in_user
        unless logged_in?
          flash[:notice] = "Please log in"
          redirect_to login_url
        end
    end 

      # Forgets a persistent session.
      def forget(user)
          user.forget
          cookies.delete(:user_id)
          cookies.delete(:remember_token)
      end

      # Logs out the current user.
      def log_out
          forget(current_user)
          @current_user = nil
      end

      def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
end
  def store_location
    session[:return_to] = request.fullpath
end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
 module UsersHelper

      # Returns the Gravatar (http://gravatar.com/) for the given user.
      def gravatar_for(user, options = { size: 50 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
      end 

    end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Easy Job", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Search", search_path %></li>
            <li><%= link_to "Users", users_path %></li>
            <% if logged_in? %>
              
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
    <html>
      <head>
        <title>Easy Job | <%= yield(:title) %></title>
        <%= stylesheet_link_tag 'application', media: 'all',
                                               'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <!--[if lt IE 9]>
          <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
          </script>
        <![endif]-->
      </head>
      <body>
        <header class="navbar navbar-fixed-top navbar-inverse">
          <%= render 'layouts/header' %>
          <div class="container">
            <%= link_to "Easy Job", '#', id: "logo" %>
            <nav>
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Home",   '#' %></li>
                <li><%= link_to "Search",   '#' %></li>
                <li><%= link_to "Log in", '#' %></li>
              </ul>
            </nav>
          </div>
        </header>
        <div class="container">
          <% flash.each do |message_type, message| %>   
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>                                      
          <%= yield %>
          
        </div>
      </body>
    </html>

app/views/shared/_error2_messages.html.erb
<% if @user.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
      <ol class="microposts">
        <%= render @feed_items %>
      </ol>
    <% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <%= f.text_area :content, placeholder: "Compose new micropost..." %>
      </div>
      <%= f.submit "Post", class: "btn btn-primary" %>
    <% end %>

app/views/shared/_user_info.html.erb
 <%= link_to gravatar_for(current_user, size: 50), user_path(current_user) %>
    <h1><%= current_user.name %></h1>
    <span><%= link_to "view my profile", current_user %></span>
    <span><%= pluralize(current_user.microposts.count, "micropost") %></span>